name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          output_action: gist
          committer_gist: bed94a881010802c51a0310b7f35049a
          plugin_traffic: yes
          plugin_notable_indepth: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: X
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://afonsojramos.me
          config_timezone: Europe/Lisbon
          token: ${{ secrets.METRICS_TOKEN }}
